# .github/workflows/pages.yml  ── build & deploy d2l-book to GitHub Pages
name: Build & Deploy d2l-book

on:
  pull_request:
    branches: [prod]
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [prod]
  workflow_dispatch:

permissions:
  contents: read
  pages:    write
  id-token: write

# Refined concurrency:
# - For PRs: cancel outdated runs to save resources.
# - For the 'prod' branch: let runs complete.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/prod' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: 'latest'

      # OPTIMIZATION: Use a dedicated action with caching for TeX Live.
      # The first run will be slow, but subsequent runs will be much faster.
      - name: Set up TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          version: 2024
          cache: true
          packages: scheme-full # scheme-full is large but robust for d2l-book

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.13'
          # OPTIMIZATION: Cache pip dependencies
          cache: 'pip'

      # OPTIMIZATION: Consolidate all pip install commands into one step
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          # Compatibility pins for d2lbook/Sphinx stack
          pip install --force-reinstall \
              "d2lbook" \
              "sphinx==5.3.0" \
              "docutils==0.19" \
              "pybtex==0.24.0" \
              "pybtex-docutils==1.0.3"

      - name: Build d2l-book (HTML + PDF)
        run: |
          d2lbook build html
          d2lbook build pdf

      - name: Copy PDF to site root for download
        run: cp dist/pdf/Apprentissage-Automatisé.pdf dist/html/Apprentissage-Automatisé.pdf

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/html

  # No changes needed for the deployment job
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/prod'
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4