# .github/workflows/pages.yml  ── build & deploy d2l-book to GitHub Pages
name: Build & Deploy d2l-book

on:
  pull_request:
    # The PR’s *target* branch must be prod
    branches:
      - prod
    # Optional but explicit: run on every change that could lead to a merge
    types: [opened, synchronize, reopened, ready_for_review]
  push:            # publish whenever prod is updated
    branches: [prod]
  workflow_dispatch:

permissions:
  contents: read
  pages:    write
  id-token: write      # required by deploy-pages

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Tell Pages what branch/path to expect and inject the BASE_PATH env var
      - uses: actions/configure-pages@v5
      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: 'latest'
      
      # CORRECTED ACTION: Pinning to a specific version for reliability.
      - name: Set up TeX Lived
        uses: xu-cheng/texlive-action@v3
        with:
          os: debian               # debian|alpine
          texlive_version: latest # or 'latest'
          run: |
            # install Python & d2lbook *inside* the container
            apt-get update -qq
            apt-get install -y python3-pip
            pip install d2lbook
            d2lbook build html
            d2lbook build pdf

      # ───────────────────────────────────────────────
      # - name: Install TeX Live (latexmk, fonts, bibtex…)
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y texlive-full
      #     # sudo apt-get install -y \
      #     #     latexmk \
      #     #     texlive-latex-base \
      #     #     texlive-latex-recommended \
      #     #     texlive-latex-extra \
      #     #     texlive-fonts-recommended \
      #     #     texlive-fonts-extra \
      #     #     texlive-bibtex-extra
      # ───────────────────────────────────────────────
      # - name: Set up TeX Live
      #   uses: teatimeguest/setup-texlive-action@v2
      #   with:
      #     version: 2024       # or 'latest'
      #     cache:  true        # speed up subsequent builds
      #     packages: |
      #       scheme-full       # full TL incl. bibtex, fonts, latexmk

      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10.13'

      # - name: Install deps
      #   run: |
      #     pip install d2lbook
      #     pip install -r requirements.txt
      #     # --- compatibility pins ----------------------------------
      #     # sphinxcontrib-bibtex needs the helper that vanished in 0.25
      #     # 3. Compatibility pins for the d2lbook/Sphinx stack  ▼▼▼
      #     #    - Sphinx 5.3 needs docutils < 0.20
      #     #    - sphinxcontrib-bibtex needs Pybtex < 0.25
      #     pip install --force-reinstall \
      #         "sphinx==5.3.0" \
      #         "docutils==0.19" \
      #         "pybtex==0.24.0" \
      #         "pybtex-docutils==1.0.3"
      #     # ----------------------------------------------------------


      # - uses: xu-cheng/texlive-action@v3
      #   with:
      #     os: debian            # debian|alpine
      #     texlive_version: 2024 # or 'latest'
      #     run: |
      #       # install Python & d2lbook *inside* the container
      #       apt-get update -qq
      #       apt-get install -y python3-pip
      #       pip install d2lbook
      #       d2lbook build html
      #       d2lbook build pdf

      # - name: Build d2l-book (HTML + PDF)
      #   run: |
      #     d2lbook build html
      #     # d2lbook build pdf        

      - name: Copy PDF to site root
        run: cp dist/pdf/book.pdf dist/html/book.pdf

      - name: Upload static site (dist/html)
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/html          # ← the folder that must be served   [oai_citation:0‡GitHub](https://github.com/actions/upload-pages-artifact)

  # Deployment job
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/prod'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4